services: 
  payment-system:
    build: .
    environment: 
      - APP_ENV=production
      - APP_KEY=yIcTghI5UqQY6z3IjTCupEbHMYPH73gJ
      - APP_DEBUG=true
      - DB_CONNECTION=pgsql
      - DB_HOST=payment-system-db
      - DB_PORT=5432
      - DB_DATABASE=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
    command: ["/bin/sh", "-c", "sleep 10 && php artisan migrate --force && php -S 0.0.0.0:80 -t public"]
    ports:
      - "8091:80"
    depends_on:
      - payment-system-db
  payment-system-db:
    image: "postgres:14.1-alpine"
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - payment-system-db:/var/lib/postgresql/data
volumes: 
  payment-system-db:
